### PR TITLE
i18n / Add Hebrew and RTL support.

### PR DESCRIPTION
**Pull request by LehRan**

### CODE REVIEW

**Comment by clementcontet** [comment]
Thanks for the PR!
I merge it right away, but I have a few fixes to do on the RTL layout before I can deploy the update (I can't figure out a way to use RTL version of Bootstrap depending on language)

**Comment by clementcontet** [comment]
It is now deployed after a few fixes and layout workarounds.
Don't hesitate to tell me if you find issues!
BTW: I just realized I didn't internationalize "min" in the game header, is it problematic?

**Comment by LehRan** [comment]
Thanks a lot Clément.
I really like the app.
I suggest to add it to blockly.games to increase its usage.

* I'd translate "min" as well but it's certainly not a deal breaker.

Keep on the good work,
Ran.

**Comment by clementcontet** [comment]
Thanks!

Can you give me the translation for "min"? I'll add it in next release.

As for Blockly games, I was in contact with Blockly team and they proposed to add SuperCodingBall to the "built with Blockly" carousel (I guess it's how you discovered the game).
But "Blockly games" only hosts games that are developed by the team (https://github.com/google/blockly-games).

**Comment by LehRan** [comment]
minutes = דקות
Got it about the blockly games.

**Comment by clementcontet** [comment]
> minutes = דקות

Thanks, implemented in https://github.com/Orange-OpenSource/super-coding-ball/commit/2772ba235e5a3df1755b9097a33972ef8c286805

**Pull request merged**
